import { LaunchOptions } from "./types";

export const defaultLaunchOptions: LaunchOptions = {
  deviceSelection: {
    connectionMode: "serial",
    tcpipAddress: "",
    captureSource: "display",
  },
  videoSettings: {
    enabled: true,
    maxSize: "1920",
    bitRate: "8M",
    maxFps: "60",
    codec: "h264",
    encoder: "",
    lockOrientation: false,
    hFlip: false,
    orientation: "0",
    displayBufferMs: "50",
    displayId: "0",
  },
  cameraMode: {
    cameraId: "",
    facing: "",
    size: "",
    fps: "30",
    aspectRatio: "",
    highSpeed: false,
  },
  audioSettings: {
    enabled: true,
    source: "output",
    bitRate: "128K",
    codec: "opus",
    encoder: "",
    bufferMs: "50",
    duplicationTarget: "off",
    audioDuplicationTarget: "off",
  },
  windowBehavior: {
    fullscreen: false,
    alwaysOnTop: false,
    borderless: false,
    windowTitle: "",
    windowX: "",
    windowY: "",
    windowWidth: "",
    windowHeight: "",
    disableScreensaver: false,
  },
  recording: {
    enabled: false,
    format: "mkv",
    timeLimit: "",
    noPlayback: false,
    noWindow: false,
  },
  inputControl: {
    noControl: false,
    showTouches: false,
    stayAwake: false,
    turnScreenOff: false,
    powerOffOnClose: false,
    screenOffTimeout: "",
    keyboardMode: "sdk",
    mouseMode: "sdk",
    gamepadMode: "disabled",
    otg: false,
  },
  displayFeatures: {
    printFps: false,
  },
  diagnostics: {
    requireAudio: false,
    noDownsizeOnError: false,
    extraArgs: "",
  },
};
