// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBundleHealth():Promise<main.BundleHealth>;

export function GetInstanceLogs(arg1:string,arg2:number):Promise<Array<main.InstanceLogLine>>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function Greet(arg1:string):Promise<string>;

export function ListDevices():Promise<Array<main.Device>>;

export function ListInstances():Promise<Array<main.InstanceSummary>>;

export function RefreshEnvironment():Promise<main.SystemStatus>;

export function StartInstance(arg1:main.LaunchRequest):Promise<main.InstanceSummary>;

export function StopAllInstances():Promise<void>;

export function StopInstance(arg1:string):Promise<void>;
