// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBundleHealth() {
  return window['go']['main']['App']['GetBundleHealth']();
}

export function GetInstanceLogs(arg1, arg2) {
  return window['go']['main']['App']['GetInstanceLogs'](arg1, arg2);
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function RefreshEnvironment() {
  return window['go']['main']['App']['RefreshEnvironment']();
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopAllInstances() {
  return window['go']['main']['App']['StopAllInstances']();
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}
